name: 【HuggingFace_n8n】daily 08:00 TPE

on:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 UTC；台北時間 08:00
  workflow_dispatch: {}

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Wake & verify n8n on HuggingFace
        shell: bash
        run: |
          set -Eeuo pipefail

          SPACE_URL="https://cleoliu-tw-n8n.hf.space"
          HEALTH_PATH="/healthz"
          MAX_WAIT_SECONDS=300
          POLL_INTERVAL_SECONDS=10

          # 先用 GET 觸發冷啟動（避免快取）
          curl -fsSL "${SPACE_URL}/?t=$(date +%s)" >/dev/null || true

          start_ts=$(date +%s)
          deadline=$(( start_ts + MAX_WAIT_SECONDS ))

          check_health() {
            local status
            status=$(curl -s -o /dev/null -w "%{http_code}" "${SPACE_URL}${HEALTH_PATH}?t=$(date +%s)" || true)
            if [[ "$status" == "200" ]]; then
              echo "healthz OK (200)"
              return 0
            elif [[ "$status" == "401" || "$status" == "404" ]]; then
              echo "healthz not accessible (status $status) → fallback to homepage"
              return 2
            else
              echo "healthz status: $status"
              return 1
            fi
          }

          check_home() {
            local body
            body=$(curl -fsSL "${SPACE_URL}/?t=$(date +%s)" || true)
            # HF 睡眠/喚醒頁的特徵字樣
            if echo "$body" | grep -qiE "sleep|waking|starting|This Space is sleeping"; then
              return 1
            fi
            # n8n 頁面常含 "n8n"；沒看到也可能是自訂頁，但只要不是睡眠頁就當 OK
            if echo "$body" | grep -qi "n8n"; then
              return 0
            fi
            return 0
          }

          while true; do
            now=$(date +%s)
            if (( now >= deadline )); then
              echo "Timed out after ${MAX_WAIT_SECONDS}s waiting for Space to be live"
              exit 1
            fi

            if check_health; then
              echo "Space is live (via /healthz)."
              break
            else
              rc=$?
              if [[ $rc -eq 2 ]]; then
                if check_home; then
                  echo "Space is live (via homepage)."
                  break
                fi
              fi
            fi

            echo "Not ready yet; sleeping ${POLL_INTERVAL_SECONDS}s…"
            sleep "${POLL_INTERVAL_SECONDS}"
          done

          # 最後再 ping 一次（可省略）
          curl -I --max-time 20 "${SPACE_URL}/?t=$(date +%s)" || true
